import AlertsTable from "../components/AlertsTable";
import EventsTable from "../components/EventsTable";
import MetricCard from "../components/MetricCard";

// Overview page with summary cards plus the latest events and alerts.
export default function DashboardPage({
  events,
  alerts,
  loading,
  error,
}) {
  const highAlerts = alerts.filter((alert) => alert.severity === "HIGH").length;
  const latestEvents = events.slice(0, 5);
  const latestAlerts = alerts.slice(0, 5);

  if (loading) {
    return <section className="state-panel">Loading dashboard data...</section>;
  }

  if (error) {
    return <section className="state-panel error">{error}</section>;
  }

  return (
    <div className="stack">
      <section className="metrics-grid">
        <MetricCard label="Total Events" value={events.length} accent="amber" />
        <MetricCard label="Total Alerts" value={alerts.length} accent="red" />
        <MetricCard label="High Alerts" value={highAlerts} accent="charcoal" />
        <MetricCard
          label="Unique Hosts"
          value={new Set(events.map((event) => event.host)).size}
          accent="teal"
        />
      </section>

      <section className="panel">
        <div className="panel-header">
          <h2>Latest Events</h2>
          <p>The newest five events received by the backend.</p>
        </div>
        {latestEvents.length ? (
          <EventsTable events={latestEvents} />
        ) : (
          <div className="state-panel">No events yet.</div>
        )}
      </section>

      <section className="panel">
        <div className="panel-header">
          <h2>Latest Alerts</h2>
          <p>Alerts generated by correlation rules in the backend.</p>
        </div>
        {latestAlerts.length ? (
          <AlertsTable alerts={latestAlerts} />
        ) : (
          <div className="state-panel">No alerts yet.</div>
        )}
      </section>
    </div>
  );
}
